### NumPy学习笔记

### ndarry的创建：

1.通过array函数创建

In [2]:
import numpy as np

In [11]:
data1 = [0,1,2,3,1.1]
arr1 = np.array(data1)
arr1

array([0. , 1. , 2. , 3. , 1.1])

通过嵌套序列方式创建

In [10]:
data2 = [[1,2,3],[4,5,6]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

2.通过zeros函数创建

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

3.通过ones函数创建

In [16]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

4.通过empty函数创建

In [28]:
np.empty(5)

array([0. , 1. , 2. , 3. , 1.1])

In [25]:
np.empty((2,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

5.arange函数：类似range函数，通过开始值、终值和步长创建数组

In [30]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

6.linspace函数：通过指定开始值、终值和元素个数来创建一维数组，可以通过endpoint关键字指定是否包括终值，缺省设置是包括终值

In [33]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

7.logspace函数：和linspace类似，不过它创建等比数列

In [35]:
np.logspace(0,2,5)

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])

8.random函数：随机创建数组

In [36]:
np.random.random(10)

array([0.60751347, 0.29262802, 0.48379076, 0.06987773, 0.09515098,
       0.1943465 , 0.46335728, 0.46320678, 0.81314993, 0.51329606])

In [40]:
np.random.random((2,2,3))

array([[[0.06608054, 0.55363782, 0.62406291],
        [0.77318127, 0.58557065, 0.17148664]],

       [[0.79126153, 0.83586225, 0.59518475],
        [0.60087036, 0.13638575, 0.7900084 ]]])

In [45]:
arr2.ndim

2

In [46]:
arr2.shape

(2, 3)

In [47]:
arr2.dtype

dtype('int32')

In [48]:
arr2.size

6

### ndarry的数据类型

In [57]:
data3 = np.array([1,2,3,4,5])
data3
data3.dtype

dtype('int32')

In [59]:
data4 = data3.astype(float)
data4.dtype

dtype('float64')

### 数组与标量、数组直接的运算

+ 矢量化：不需要编写循环，可实现对数据的批量计算。性能上比Python快一两个数量级，大小相等的任何算术运算都会应用到元素级


1.数组与标量之间的运算


In [ ]:
arr1 = np.array([1,2,3,4,5])
arr1+2

In [9]:
from __future__ import division
1/arr1

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ])

2.大小相等数组之间的运算，即大小相等的数组之间的运算，为元素级运算。位置相同的元素之间，运算结果组成一个新的数组。运算结果的位置跟操作数位置相同

In [13]:
arr2 =  np.array([5,6,7,8,9])
arr1+arr2

array([ 6,  8, 10, 12, 14])

In [14]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr4 = np.array([[1,2,3],[4,5,6]])
arr3 + arr4

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [15]:
arr3 - arr4

array([[0, 0, 0],
       [0, 0, 0]])

In [16]:
arr3 * arr4 

array([[ 1,  4,  9],
       [16, 25, 36]])

In [17]:
arr3 / arr4 

array([[1., 1., 1.],
       [1., 1., 1.]])

3.数组的矩阵积

- 矩阵积：不是元素级的运算，两个二维（多维）矩阵，第一个矩阵的列数与第二个矩阵的行数相同，可以进行矩阵乘法，即矩阵积。

In [21]:
arr1 = np.array([[1,2,3],[1,2,3]])
arr2 = np.array([[1,2],[1,1],[2,1]])
arr1.dot(arr2)

array([[9, 7],
       [9, 7]])

In [22]:
np.dot(arr1,arr2)

array([[9, 7],
       [9, 7]])

- 设A为的m×p的矩阵，B为p×n的矩阵，那么称m×n的矩阵C为矩阵A与B的乘积，记作C=AB，其中矩阵C中的第i行第j列元素可以表示为：